'use client';

import { useState } from 'react';
// jsPDF will be dynamically imported to avoid SSR/Turbopack build issues

// Interface untuk tipe data
interface QuestionForm {
  material: string;
  questionType: 'multiple-choice' | 'essay';
  questionCount: number;
  difficulty: 'easy' | 'medium' | 'hard';
}

interface GeneratedQuestion {
  question: string;
  options?: string[];
  correctAnswer?: string;
  explanation?: string;
}

interface APIResponse {
  success: boolean;
  data?: {
    questions: GeneratedQuestion[];
  };
  error?: string;
}

export default function Home() {
  // State untuk form input
  const [formData, setFormData] = useState<QuestionForm>({
    material: '',
    questionType: 'multiple-choice',
    questionCount: 5,
    difficulty: 'medium'
  });

  // State untuk UI
  const [isLoading, setIsLoading] = useState(false);
  const [generatedQuestions, setGeneratedQuestions] = useState<GeneratedQuestion[]>([]);
  const [error, setError] = useState<string>('');

  // Handler untuk perubahan form
  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  // Handler untuk download soal sebagai TXT
  const handleDownloadQuestions = () => {
    if (generatedQuestions.length === 0) return;

    // Buat konten file berdasarkan jenis soal
    let content = '';
    const { questionType } = formData;
    
    // Header
    content += `ExamCraft AI\n`;
    content += `=====================================\n\n`;
    content += `Jenis Soal: ${getQuestionTypeLabel(questionType)}\n`;
    content += `Jumlah Soal: ${generatedQuestions.length}\n`;
    content += `Tingkat Kesulitan: ${getDifficultyLabel(formData.difficulty)}\n`;
    content += `Tanggal: ${new Date().toLocaleString('id-ID')}\n\n`;
    content += `-------------------------------------\n\n`;

    // Generate soal berdasarkan jenis
    generatedQuestions.forEach((question, index) => {
      content += `SOAL ${index + 1}\n`;
      content += `${'='.repeat(50)}\n\n`;
      content += `Pertanyaan:\n${question.question}\n\n`;

      if (questionType === 'multiple-choice' && question.options) {
        content += `Pilihan Jawaban:\n`;
        question.options.forEach((option, optIndex) => {
          const letter = String.fromCharCode(65 + optIndex);
          const isCorrect = option === question.correctAnswer;
          content += `  ${letter}. ${option}${isCorrect ? ' ✓' : ''}\n`;
        });
        content += `\nKunci Jawaban: ${question.correctAnswer}\n\n`;
      } else if (questionType === 'essay') {
        content += `[Jawaban esai - lihat penjelasan untuk petunjuk]\n\n`;
      }

      if (question.explanation) {
        content += `Penjelasan:\n${question.explanation}\n\n`;
      }
      content += `${'-'.repeat(50)}\n\n`;
    });

    // Footer
    content += `=====================================\n`;
    content += `Generated by ExamCraft AI\n`;
    content += `Powered by OpenRouter AI\n`;

    // Download file
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `examcraft-questions-${questionType}-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // Handler untuk download soal sebagai PDF
  const handleDownloadPDF = async () => {
    if (generatedQuestions.length === 0) return;

    // Dynamic import to avoid SSR/Turbopack issues
    const jsPDFModule: any = await import('jspdf');
    const jsPDFConstructor = jsPDFModule.jsPDF || jsPDFModule.default || jsPDFModule;

    const { questionType } = formData;
    const doc = new jsPDFConstructor();

    // Set font untuk mendukung Unicode (Indonesian)
    doc.setFont('helvetica');

    let yPosition = 20;
    const lineHeight = 7;
    const pageHeight = doc.internal.pageSize.height;

    // Header
    doc.setFontSize(20);
    doc.text('ExamCraft AI', 105, yPosition, { align: 'center' });
    yPosition += 15;

    doc.setFontSize(12);
    doc.text(`Jenis Soal: ${getQuestionTypeLabel(questionType)}`, 20, yPosition);
    yPosition += lineHeight;
    doc.text(`Jumlah Soal: ${generatedQuestions.length}`, 20, yPosition);
    yPosition += lineHeight;
    doc.text(`Tingkat Kesulitan: ${getDifficultyLabel(formData.difficulty)}`, 20, yPosition);
    yPosition += lineHeight;
    doc.text(`Tanggal: ${new Date().toLocaleString('id-ID')}`, 20, yPosition);
    yPosition += lineHeight * 2;

    // Generate soal
    generatedQuestions.forEach((question, index) => {
      // Check if we need a new page
      if (yPosition > pageHeight - 50) {
        doc.addPage();
        yPosition = 20;
      }
      
      // Soal number
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text(`SOAL ${index + 1}`, 20, yPosition);
      yPosition += lineHeight * 1.5;
      
      // Pertanyaan
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      const questionLines = doc.splitTextToSize(question.question, 170);
      questionLines.forEach((line: string) => {
        if (yPosition > pageHeight - 30) {
          doc.addPage();
          yPosition = 20;
        }
        doc.text(line, 20, yPosition);
        yPosition += lineHeight;
      });
      yPosition += lineHeight;
      
      // Pilihan jawaban untuk multiple choice
      if (questionType === 'multiple-choice' && question.options) {
        question.options.forEach((option, optIndex) => {
          if (yPosition > pageHeight - 30) {
            doc.addPage();
            yPosition = 20;
          }
          const letter = String.fromCharCode(65 + optIndex);
          const isCorrect = option === question.correctAnswer;
          const optionText = `${letter}. ${option}${isCorrect ? ' (Benar)' : ''}`;
          const optionLines = doc.splitTextToSize(optionText, 150);
          optionLines.forEach((line: string) => {
            if (yPosition > pageHeight - 30) {
              doc.addPage();
              yPosition = 20;
            }
            doc.text(line, 25, yPosition);
            yPosition += lineHeight;
          });
        });
        yPosition += lineHeight;
        doc.text(`Kunci Jawaban: ${question.correctAnswer}`, 20, yPosition);
        yPosition += lineHeight * 2;
      } else if (questionType === 'essay') {
        if (yPosition > pageHeight - 30) {
          doc.addPage();
          yPosition = 20;
        }
        doc.text('[Jawaban esai - lihat penjelasan untuk petunjuk]', 20, yPosition);
        yPosition += lineHeight * 2;
      }
      
      // Penjelasan
      if (question.explanation) {
        if (yPosition > pageHeight - 40) {
          doc.addPage();
          yPosition = 20;
        }
        doc.setFont('helvetica', 'bold');
        doc.text('Penjelasan:', 20, yPosition);
        yPosition += lineHeight;
        doc.setFont('helvetica', 'normal');
        const explanationLines = doc.splitTextToSize(question.explanation, 170);
        explanationLines.forEach((line: string) => {
          if (yPosition > pageHeight - 30) {
            doc.addPage();
            yPosition = 20;
          }
          doc.text(line, 20, yPosition);
          yPosition += lineHeight;
        });
        yPosition += lineHeight;
      }
      
      // Separator
      yPosition += lineHeight;
      if (yPosition < pageHeight - 30) {
        doc.text('--------------------------------------------------', 20, yPosition);
        yPosition += lineHeight * 2;
      }
    });
    
    // Footer
    const lastPage = doc.internal.getNumberOfPages();
    doc.setPage(lastPage);
    yPosition = pageHeight - 20;
    doc.setFontSize(10);
    doc.text('Generated by ExamCraft AI', 105, yPosition, { align: 'center' });
    yPosition += lineHeight;
    doc.text('Powered by OpenRouter AI', 105, yPosition, { align: 'center' });
    
    // Download PDF
    doc.save(`examcraft-questions-${questionType}-${new Date().toISOString().split('T')[0]}.pdf`);
  };

  // Handler untuk generate soal
  const handleGenerateQuestions = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.material.trim()) {
      setError('Materi pembelajaran harus diisi');
      return;
    }

    if (formData.material.trim().length < 50) {
      setError('materi terlalu singkat');
      return;
    }

    setIsLoading(true);
    setError('');
    setGeneratedQuestions([]);

    try {
      const response = await fetch('/api/generate-questions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(formData)
      });

      const result: APIResponse = await response.json();

      if (result.success && result.data) {
        setGeneratedQuestions(result.data.questions);
        setError('');
      } else {
        setError(result.error || 'Gagal menghasilkan soal');
      }
    } catch (err) {
      setError('Terjadi kesalahan. Silakan coba lagi.');
    } finally {
      setIsLoading(false);
    }
  };

  // Helper functions
  const getQuestionTypeLabel = (type: string) => {
    switch (type) {
      case 'multiple-choice': return 'Pilihan Ganda';
      case 'essay': return 'Esai';
      default: return 'Umum';
    }
  };

  const getDifficultyLabel = (difficulty: string) => {
    switch (difficulty) {
      case 'easy': return 'Mudah';
      case 'medium': return 'Sedang';
      case 'hard': return 'Sulit';
      default: return 'Sedang';
    }
  };

  // Render soal berdasarkan jenis
  const renderQuestion = (question: GeneratedQuestion, index: number) => {
    const { questionType } = formData;

    return (
      <div key={index} className="border-2 border-gray-200 rounded-xl p-6 mb-6 hover:border-blue-300 transition-colors bg-gradient-to-r from-white to-blue-50">
        <div className="flex items-center mb-4">
          <div className="bg-blue-600 text-white w-8 h-8 rounded-full flex items-center justify-center font-bold mr-3">
            {index + 1}
          </div>
          <h4 className="font-bold text-lg text-gray-800">Soal {index + 1}</h4>
        </div>
        
        <div className="bg-white p-4 rounded-lg mb-4 border border-gray-100">
          <p className="text-gray-800 leading-relaxed">{question.question}</p>
        </div>

        {questionType === 'multiple-choice' && question.options && (
          <div className="space-y-3 mb-4">
            {question.options.map((option, optIndex) => (
              <label key={optIndex} className="flex items-center space-x-3 p-3 rounded-lg hover:bg-blue-50 transition-colors cursor-pointer border border-gray-200">
                <input
                  type="radio"
                  name={`question-${index}`}
                  value={option}
                  className="w-4 h-4 text-blue-600 focus:ring-blue-500"
                />
                <span className="text-gray-700 font-medium">{String.fromCharCode(65 + optIndex)}. {option}</span>
              </label>
            ))}
          </div>
        )}

        

        {questionType === 'essay' && (
          <div className="mb-4">
            <textarea
              placeholder="Tulis jawaban esai Anda di sini..."
              rows={5}
              className="w-full border-2 border-gray-300 rounded-xl px-4 py-3 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 transition-all text-gray-700 resize-none"
            />
          </div>
        )}

        {question.explanation && (
          <div className="bg-gradient-to-r from-blue-50 to-indigo-50 border-2 border-blue-200 rounded-xl p-4">
            <div className="flex items-start space-x-2">
              <span className="text-blue-600 text-lg">💡</span>
              <div>
                <strong className="text-blue-800">Petunjuk:</strong>
                <p className="text-blue-700 mt-1">{question.explanation}</p>
              </div>
            </div>
          </div>
        )}
      </div>
    );
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 py-8">
      <div className="max-w-4xl mx-auto px-4">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="bg-white rounded-2xl shadow-lg p-8 mb-6">
            <h1 className="text-4xl font-bold text-gray-800 mb-3">
              🤖 ExamCraft AI
            </h1>
            <p className="text-lg text-gray-600 leading-relaxed">
              Buat soal ujian otomatis dari materi pembelajaran menggunakan teknologi AI
            </p>
            <div className="mt-4 flex justify-center space-x-4">
              <div className="bg-blue-100 text-blue-800 px-4 py-2 rounded-full text-sm font-medium">
                ⚡ Cepat & Otomatis
              </div>
                <div className="bg-green-100 text-green-800 px-4 py-2 rounded-full text-sm font-medium">
                  📚 2 Jenis Soal
                </div>
              <div className="bg-purple-100 text-purple-800 px-4 py-2 rounded-full text-sm font-medium">
                🎯 AI Powered
              </div>
            </div>
          </div>
        </div>

        {/* Form Input */}
        <div className="bg-white rounded-2xl shadow-lg p-8 mb-8">
          <form onSubmit={handleGenerateQuestions}>
            {/* Input Materi */}
            <div className="mb-8">
              <label className="block text-lg font-semibold text-gray-800 mb-3">
                📝 Materi Pembelajaran
              </label>
              
              <div>
                <textarea
                  name="material"
                  value={formData.material}
                  onChange={handleInputChange}
                  placeholder="Masukkan materi pembelajaran di sini...&#10;&#10;Contoh:&#10;Photosintesis adalah proses biologi yang mengubah energi cahaya menjadi energi kimia. Proses ini terjadi di kloroplas dan melibatkan klorofil. Hasil utama fotosintesis adalah glukosa dan oksigen."
                  className="w-full border-2 border-gray-300 rounded-xl px-4 py-3 h-40 resize-none focus:border-blue-500 focus:ring-2 focus:ring-blue-200 transition-all text-gray-700"
                  required
                />
                <div className="mt-2 text-sm text-gray-500">
                  📝 Ketik materi pembelajaran minimal 50 karakter
                </div>
              </div>
            </div>

            {/* Pengaturan Soal */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
              {/* Jenis Soal */}
              <div>
                <label className="block text-lg font-semibold text-gray-800 mb-3">
                  📋 Jenis Soal
                </label>
                <select
                  name="questionType"
                  value={formData.questionType}
                  onChange={handleInputChange}
                  className="w-full border-2 border-gray-300 rounded-xl px-4 py-3 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 transition-all text-gray-700 font-medium"
                >
                  <option value="multiple-choice">🔘 Pilihan Ganda</option>
                  <option value="essay">📄 Esai</option>
                </select>
              </div>

              {/* Jumlah Soal */}
              <div>
                <label className="block text-lg font-semibold text-gray-800 mb-3">
                  🔢 Jumlah Soal
                </label>
                <input
                  type="number"
                  name="questionCount"
                  value={formData.questionCount}
                  onChange={handleInputChange}
                  min="1"
                  max="10"
                  className="w-full border-2 border-gray-300 rounded-xl px-4 py-3 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 transition-all text-gray-700 font-medium"
                />
                <div className="mt-1 text-xs text-gray-500">1-10 soal</div>
              </div>

              {/* Tingkat Kesulitan */}
              <div>
                <label className="block text-lg font-semibold text-gray-800 mb-3">
                  📈 Tingkat Kesulitan
                </label>
                <select
                  name="difficulty"
                  value={formData.difficulty}
                  onChange={handleInputChange}
                  className="w-full border-2 border-gray-300 rounded-xl px-4 py-3 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 transition-all text-gray-700 font-medium"
                >
                  <option value="easy">😊 Mudah</option>
                  <option value="medium">🎯 Sedang</option>
                  <option value="hard">🔥 Sulit</option>
                </select>
              </div>
            </div>

            {/* Error Message */}
            {error && (
              <div className="bg-red-50 border-2 border-red-200 text-red-800 px-6 py-4 rounded-xl mb-6">
                <div className="flex items-center space-x-2">
                  <span className="text-xl">⚠️</span>
                  <span className="font-medium">{error}</span>
                </div>
              </div>
            )}

            {/* Submit Button */}
            <button
              type="submit"
              disabled={isLoading || !formData.material.trim()}
              className="w-full bg-gradient-to-r from-blue-600 to-indigo-600 text-white py-4 rounded-xl font-bold text-lg hover:from-blue-700 hover:to-indigo-700 disabled:from-gray-400 disabled:to-gray-500 disabled:cursor-not-allowed transition-all shadow-lg hover:shadow-xl transform hover:-translate-y-1"
            >
              {isLoading ? (
                <div className="flex items-center justify-center space-x-2">
                  <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                  <span>🤖 Menghasilkan Soal...</span>
                </div>
              ) : (
                <div className="flex items-center justify-center space-x-2">
                  <span>✨</span>
                  <span>Hasilkan Soal dengan AI</span>
                  <span>✨</span>
                </div>
              )}
            </button>
          </form>
        </div>

        {/* Hasil Soal */}
        {generatedQuestions.length > 0 && (
          <div className="bg-white rounded-2xl shadow-lg p-8">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-2xl font-bold text-gray-800">
                📚 Hasil Soal ({generatedQuestions.length} soal)
              </h2>
              <div className="bg-green-100 text-green-800 px-4 py-2 rounded-full text-sm font-medium">
                ✅ Berhasil Dibuat
              </div>
            </div>
            {generatedQuestions.map((question, index) => renderQuestion(question, index))}
            
            <div className="mt-8 flex flex-col sm:flex-row space-y-4 sm:space-y-0 sm:space-x-4">
              <button 
                onClick={handleDownloadQuestions}
                className="flex-1 bg-gradient-to-r from-green-600 to-emerald-600 text-white py-3 rounded-xl font-bold hover:from-green-700 hover:to-emerald-700 transition-all shadow-lg hover:shadow-xl transform hover:-translate-y-1"
              >
                📄 Download TXT
              </button>
              <button 
                onClick={handleDownloadPDF}
                className="flex-1 bg-gradient-to-r from-red-600 to-pink-600 text-white py-3 rounded-xl font-bold hover:from-red-700 hover:to-pink-700 transition-all shadow-lg hover:shadow-xl transform hover:-translate-y-1"
              >
                📑 Download PDF
              </button>
              <button 
                onClick={() => setGeneratedQuestions([])}
                className="flex-1 bg-gradient-to-r from-gray-600 to-gray-700 text-white py-3 rounded-xl font-bold hover:from-gray-700 hover:to-gray-800 transition-all shadow-lg hover:shadow-xl transform hover:-translate-y-1"
              >
                🔄 Buat Soal Baru
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}